### ISSUE TITLE
Order IDs, cancelling and modifying orders

### ISSUE THREAD

**Issue by shawnmitchell** [PavlosSakoglou/Exchange-Matching-Engine-Emulation#2]
An order in the book should be able to be cancelled and/or modified. The rules for order modifications are simple:

- Order cannot change sides (buy to sell or vice versa)
- Price change on an order results in loss of priority
- Size increase results in loss of priority
- Size decrease results in no change of priority

**Comment by psakoglou** [comment]
Added the following methods:

// Exchange class
void edit_trade_price(Trader * t, Request * r, std::string side, std::string instrument, double new_price);
void edit_trade_quantity(Trader * t, Request * r, std::string side, std::string instrument, long quantity);
void delete_trade(Trader * t, Request * r, std::string side, std::string instrument);

// TradeHeap class
void remove(Trader * t, Request * r);	// Remove a request from the heap
void sort();  // re-sorts the heap internally after a price/quantity modification requires so

All seem to work fine. In the DEMO1.cpp I do delete the last two available trades, and they no longer appear on the available trades print-out, and additionally I change the ask price for the remaining AMZN request to $1000, and by hard coding it I observe it is indeed changed.
